name: Build and Upload Artifacts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup CMake
      uses: actions/setup-cmake@v4
      with:
        cmake-version: '3.27.0'


    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release

    # 上传构建产物
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: build/*.exe
        # 或者多个路径：
        # path: |
        #   build/bin/
        #   build/lib/

    # 如果你有多个目录或文件，也可以多次上传
